# Generated by Django 4.0.6 on 2022-07-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at_data', models.DateField(auto_created=True)),
                ('created_at_time', models.TimeField(auto_created=True)),
                ('name', models.CharField(max_length=32)),
                ('Phone', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('select_class', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
    ]
