# Generated by Django 4.0.6 on 2022-08-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat_booling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_at_data',
            field=models.DateField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at_time',
            field=models.TimeField(auto_created=True, null=True),
        ),
    ]
