# Generated by Django 4.0.6 on 2022-07-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_classes_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facilities_title', models.CharField(max_length=32)),
                ('Facilities_description', models.TextField(max_length=300)),
                ('Facilities_icon', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(upload_to='img/upload'),
        ),
        migrations.AlterField(
            model_name='school_basic_detail',
            name='Facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='school_basic_detail',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='school_basic_detail',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='school_basic_detail',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Experience',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='Social_media_id',
            field=models.URLField(blank=True),
        ),
    ]
