# Generated by Django 4.0.6 on 2022-07-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_facilities_alter_blog_blog_img_alter_blog_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_basic_detail',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
