# Generated by Django 4.0.6 on 2022-07-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_school_basic_detail_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('about_detail', models.TextField(max_length=320)),
                ('points_1', models.CharField(blank=True, max_length=32, null=True)),
                ('points_2', models.CharField(blank=True, max_length=32, null=True)),
                ('points_3', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
