# Generated by Django 4.0.6 on 2022-07-30 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_about_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_school',
            name='about_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/upload'),
            preserve_default=False,
        ),
    ]
