# Generated by Django 4.0.6 on 2022-07-30 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_about_school_about_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about_school',
            old_name='about_img',
            new_name='about_img1',
        ),
        migrations.AddField(
            model_name='about_school',
            name='about_img2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/upload'),
            preserve_default=False,
        ),
    ]
