# Generated by Django 4.0.6 on 2022-07-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_about_img_about_school_about_img1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('about', models.TextField(max_length=300)),
                ('images', models.ImageField(upload_to='img/upload')),
            ],
        ),
    ]
