# Generated by Django 4.0.6 on 2022-07-30 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_mainheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_basic_detail',
            name='contact_description',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
