# Generated by Django 4.0.6 on 2022-07-30 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_school_basic_detail_contact_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_basic_detail',
            name='opening_Hours',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
