# Generated by Django 4.0.6 on 2022-08-02 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_school_basic_detail_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainheading',
            name='school_logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/upload'),
            preserve_default=False,
        ),
    ]
