# Generated by Django 4.0.6 on 2022-08-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_mainheading_school_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=32)),
                ('person_profession', models.CharField(max_length=32)),
                ('testimonial_data', models.TextField(max_length=300)),
                ('testimonial_verified', models.BooleanField()),
            ],
        ),
    ]
