# Generated by Django 4.0.6 on 2022-08-04 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='person_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/upload'),
            preserve_default=False,
        ),
    ]
