# Generated by Django 4.0.6 on 2023-05-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_testimonial_person_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_school',
            name='about_detail',
            field=models.TextField(max_length=3200),
        ),
        migrations.AlterField(
            model_name='about_school',
            name='title',
            field=models.CharField(max_length=320),
        ),
        migrations.AlterField(
            model_name='blog',
            name='detail',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_description',
            field=models.TextField(max_length=2560),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_name',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='mainheading',
            name='about',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='mainheading',
            name='title',
            field=models.CharField(max_length=320),
        ),
        migrations.AlterField(
            model_name='school_basic_detail',
            name='address',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='name',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teaching_subject',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='person_img',
            field=models.ImageField(blank=True, upload_to='img/upload'),
        ),
    ]
