# Generated by Django 4.0.6 on 2023-05-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
