# Generated by Django 4.0.6 on 2023-05-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dis',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
